const BoredFishingSitesList = [
    "https://sliding.toys/mystic-square/8-puzzle/daily/",
    "https://longdogechallenge.com/",
    "https://maze.toys/mazes/mini/daily/",
    "https://optical.toys",
    "https://paint.toys/",
    "https://puginarug.com",
    "https://alwaysjudgeabookbyitscover.com",
    "https://clicking.toys/flip-grid/neat-nine/3-holes/",
    "https://weirdorconfusing.com/",
    "https://checkbox.toys/scale/",
    "https://memory.toys/classic/easy/",
    "https://binarypiano.com/",
    "https://mondrianandme.com/",
    "https://onesquareminesweeper.com/",
    "https://cursoreffects.com",
    "http://floatingqrcode.com/",
    "https://thatsthefinger.com/",
    "https://cant-not-tweet-this.com/",
    "http://heeeeeeeey.com/",
    "http://corndog.io/",
    "http://eelslap.com/",
    "http://www.staggeringbeauty.com/",
    "http://burymewithmymoney.com/",
    "https://smashthewalls.com/",
    "https://jacksonpollock.org/",
    "http://endless.horse/",
    "http://drawing.garden/",
    "https://www.trypap.com/",
    "http://www.republiquedesmangues.fr/",
    "http://www.movenowthinklater.com/",
    "https://sliding.toys/klotski/easy-street/",
    "https://paint.toys/calligram/",
    "https://checkboxrace.com/",
    "http://www.rrrgggbbb.com/",
    "http://www.koalastothemax.com/",
    "https://rotatingsandwiches.com/",
    "http://www.everydayim.com/",
    "http://randomcolour.com/",
    "http://maninthedark.com/",
    "http://cat-bounce.com/",
    "http://chrismckenzie.com/",
    "https://thezen.zone/",
    "http://ninjaflex.com/",
    "http://ihasabucket.com/",
    "http://corndogoncorndog.com/",
    "http://www.hackertyper.com/",
    "https://pointerpointer.com",
    "http://imaninja.com/",
    "http://www.partridgegetslucky.com/",
    "http://www.ismycomputeron.com/",
    "http://www.nullingthevoid.com/",
    "http://www.muchbetterthanthis.com/",
    "http://www.yesnoif.com/",
    "http://lacquerlacquer.com",
    "http://potatoortomato.com/",
    "http://iamawesome.com/",
    "https://strobe.cool/",
    "http://thisisnotajumpscare.com/",
    "http://doughnutkitten.com/",
    "http://crouton.net/",
    "http://corgiorgy.com/",
    "http://www.wutdafuk.com/",
    "http://unicodesnowmanforyou.com/",
    "http://chillestmonkey.com/",
    "http://scroll-o-meter.club/",
    "http://www.crossdivisions.com/",
    "http://tencents.info/",
    "https://boringboringboring.com/",
    "http://www.patience-is-a-virtue.org/",
    "http://pixelsfighting.com/",
    "http://isitwhite.com/",
    "https://existentialcrisis.com/",
    "http://onemillionlols.com/",
    "http://www.omfgdogs.com/",
    "http://oct82.com/",
    "http://chihuahuaspin.com/",
    "http://www.blankwindows.com/",
    "http://tunnelsnakes.com/",
    "http://www.trashloop.com/",
    "http://spaceis.cool/",
    "http://www.doublepressure.com/",
    "http://www.donothingfor2minutes.com/",
    "http://buildshruggie.com/",
    // 'http://buzzybuzz.biz/', cert
    "http://yeahlemons.com/",
    "http://wowenwilsonquiz.com",
    // 'https://thepigeon.org/', expired
    "http://notdayoftheweek.com/",
    "http://www.amialright.com/",
    "https://optical.toys/thatcher-effect/",
    "https://greatbignothing.com/",
    "https://zoomquilt.org/",
    "https://dadlaughbutton.com/",
    "https://remoji.com/",
    "http://papertoilet.com/",
    "https://loopedforinfinity.com/",
    "https://end.city/",
    "https://www.bouncingdvdlogo.com/",
    "https://clicking.toys/peg-solitaire/english/",
    "https://toms.toys",
    "https://cat-bounce.com/",
    "http://www.koalastothemax.com",
    "https://chrismckenzie.com/",
    "https://aidn.jp/contents/",
    "https://aidn.jp/mikutap/",
    "https://aidn.jp/mikuboard/",
    "https://aidn.jp/mf/",
    "http://madebyevan.com/webgl-water",
];

const HELP_TEXT = `你可以对我说：
✅ 帮助：查看帮助文档
✅ 每日一题：查看leetcode今日题目
✅ 讲笑话：为你讲个笑话
✅ 推荐n篇掘金文章：为你推荐n篇掘金文章
✅ 无聊摸鱼：随机推荐一个无聊摸鱼网站
✅ 打新股票：查看近期即将上市的股票
✅ 随机出题：随机一道leetcode题目

🚧 更多功能正在建造中...

\n🛑 为了不打扰他人，可以添加我为好友，跟我私聊，独自享受我的专属服务`;

module.exports = { BoredFishingSitesList, HELP_TEXT };
